name: build-conda

runs:
  using: "composite"
  steps:

  - name: initializing conda environment
    uses: conda-incubator/setup-miniconda@v3
    with:
      miniforge-version: latest
      activate-environment: numl
      auto-update-conda: true
      auto-activate-base: false

  - name: getting date
    shell: bash
    id: get-date
    run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT

  - name: setting up conda environment cache
    uses: actions/cache@v3
    with:
      path: ${{ env.CONDA }}/envs
      key:
        conda-${{ runner.os }}--${{ runner.arch }}--${{
        steps.get-date.outputs.today }}-${{
        hashFiles('numl.yaml') }}-${{ env.CACHE_NUMBER
        }}
    env:
      CACHE_NUMBER: 0
    id: cache

  - name: updating conda environment
    shell: bash
    run: |
      mamba list
      mamba env update -n numl -f numl.yaml
    if: steps.cache.outputs.cache-hit != 'true'
