name: build-nugraph

runs:
  using: "composite"
  steps:
  - name: setting up conda cache
    uses: actions/cache@v3
    env:
      CACHE_NUMBER: 1
    with:
      path: ~/conda_pkgs_dir
      key:
        ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
        hashFiles('numl.yaml') }}
  - name: installing conda environment
    uses: conda-incubator/setup-miniconda@v3
    with:
      activate-environment: numl
      environment-file: numl.yaml
      miniforge-version: latest
      # conda-remove-defaults: "true"
      use-only-tar-bz2: true
  - name: installing local packages
    shell: bash
    run: |
      pip install --no-deps -e ./pynuml
      pip install --no-deps -e ./nugraph
