name: build-nugraph

inputs:
  token:
    description: "github token"
    required: true

runs:
  using: "composite"
  steps:
  - name: configuring spack cache
    uses: actions/cache@v4
    with:
      path: /opt/spack
      key: ${{ runner.os }}-spack
  - name: setting up spack
    uses: spack/setup-spack@v2
  - name: checking out nugraph spack repo
    uses: actions/checkout@v4
    with:
      repository: nugraph/numl-spack
      path: spack/var/spack/repos/numl-spack
  - name: setting spack oci permissions
    shell: bash
    run: spack -e . mirror set --oci-username ${{ github.actor }} --oci-password "${{ inputs.token }}" local-buildcache
  - name: building spack environment
    shell: bash
    run: spack -e . install
  - name: pushing packages to spack buildcache
    shell: bash
    run: spack -e . buildcache push --base-image ubuntu:latest --update-index local-buildcache
    if: ${{ !cancelled() }}
