name: build-nugraph

runs:
  using: "composite"
  steps:
  - name: setting up spack
    uses: spack/setup-spack@v2
  - name: checking out nugraph spack repo
    uses: actions/checkout@v4
    with:
      repository: nugraph/numl-spack
      path: spack/var/spack/repos/numl-spack
  - name: building spack environment
    shell: bash
    run: spack -e . install
  - name: pushing packages to spack buildcache
    shell: bash
    run: |
      spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
      spack -e . buildcache push --base-image ubuntu:latest --update-index local-buildcache
    if: ${{ !cancelled() }}
