name: build-nugraph

runs:
  using: "composite"
  steps:
  - name: installing conda environment
    uses: conda-incubator/setup-miniconda@v3
    with:
      environment-file: numl.yaml
      miniforge-version: latest
  - name: installing local packages
    shell: bash
    run: |
      pip install --no-deps -e ./pynuml
      pip install --no-deps -e ./nugraph
