{% set name = "pynuml" %}
{% set version = "24.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynuml-{{ version }}.tar.gz
  sha256: 20d2f1a07887473e67c79ecc3804b8012e22b78883199fdb0d07bb1b725b6ab0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - flit >=3.2,<4
    - pip
  run:
    - python >=3.7
    - h5py >=3.7.0
    - mpi4py
    - pandas
    - particle
    - plotly
    - pytorch >=1.12.1
    - pyg >=2.1.0

test:
  imports:
    - pynuml
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Standardised ML input processing for particle physics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vhewes
