{% set name = "nugraph" %}
{% set version = "24.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nugraph-{{ version }}.tar.gz
  sha256: e1449e4a37049cc774ad026d4f2db339eb60bb59109a11920bb65a4061915de8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - flit >=3.2,<4
    - pip
  run:
    - python >=3.10
    - matplotlib-base
    - plotly
    - pynuml ==24.7.1
    - pynvml
    - seaborn
    - pytorch >=1.12.1
    - pyg >=2.1.0
    - pytorch-lightning >=1.7.1

test:
  imports:
    - nugraph
  commands:
    - pip check
  requires:
    - pip

about:
  summary: 'NuGraph2: A Graph Neural Network for neutrino physics event reconstruction'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vhewes
